### PR TITLE
Add transaction detail page

### LINKED ISSUE #2: Transactions should have a `details` button that drops down to show more information
This detail should show the fee, the payment ID, the block height and any other info we have in the transaction object

### PR DESCRIPTION
**Pull request by krruzic**
fixes #2

### CODE REVIEW

**Comment by krruzic** [comment]
image

**Comment by crappyrules** [comment]
you will never be a woman.  just a dude in a dress

**Comment by ExtraHash** [comment]
stay off my repo crappy

**Comment by ExtraHash** [comment]
this doesn't look very mobile friendly. i like the idea, but maybe let's go for like a column type view like this

Height            17555
Fee                20.00 TRTL

etc where the right text is right justified like the current transaction list is

**Review by ExtraHash — CHANGES_REQUESTED** [review]
see comments for changes

**Comment by krruzic** [comment]
image

**Comment by ExtraHash** [comment]
still not loving it, can we use one <li> element for all of the details so there's not a border in between the details elements, and just put them on different lines with <p> tags or something. and don't use the `.heading` css class on the details, make it white background and maybe even indent it a bit to indicate that it's a sub-element of the main transaction element

**Comment by krruzic** [comment]
I've fixed the text wrapping so if you don't have any other comments this should be good to merge

**Comment by ExtraHash** [comment]
thanks for the pr's

**Pull request merged**
